name: Terraform Provision

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - 'variables.tf'
      - 'outputs.tf'
      - 'cloud-init.tpl'
      - 'terraform.tfvars'

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    env:
      # 여기에 이미 설정된 TF_VAR_* 시크릿을 그대로 매핑
      TF_VAR_username:    ${{ secrets.TF_VAR_USERNAME }}
      TF_VAR_password:    ${{ secrets.TF_VAR_PASSWORD }}
      TF_VAR_tenant_name: ${{ secrets.TF_VAR_TENANT_NAME }}
      TF_VAR_region:      ${{ secrets.TF_VAR_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve

